### ISSUE TITLE
Review by Mato

### ISSUE THREAD

**Issue by martin2117** [ingSlonik/ImproApp#1]
I like this app because of its simplicity and easy-to-use approach. I suggest following improvements:

Generator

-- Generate all things at once

Timer 

-- Restart timer from initially set time
-- Add time picker instead of text field for Custom button

Menu

-- Menu could be displayed, not expandable. (e. g. Switch at the bottom of the View) 

Language

-- Support English

Bug to fix

-- Timer pauses upon screen lock

**Comment by ingSlonik** [comment]
Hi Mato,

1. Generate all things at once: Added to next version.
2. Restart timer from the initially set time: Added to next version.
3. Add time picker instead of the text field for Custom button: It needs to decide which one I will use, unfortunately, it is not a native component of systems (just for hours).
4. Menu: Could you please send me some design suggestions :)
5. Language: It is planning, but it will take more time, if you want to help me, please do a part of that and give the pull request to me.
6. The timer pauses upon screen lock: Thank you for reporting it, it will be in next version.

P.S.: Maybe for next time, could you prepare one issue for each of this point. It will be easier to manage.
